version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - type: bind
        source: ../../
        target: /main
    working_dir: /main
    ports:
      - "8888:8888"
      - "8501:8501"
    command:
      streamlit run main.py
    environment:
        PYTHONPATH: "/main/src"
        PYTHONUNBUFFERED: 1
